# Generated by Django 5.2.8 on 2025-11-07 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(choices=[('text', '文本'), ('pdf', 'PDF'), ('image', '图片'), ('video', '视频')], max_length=10)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('uploaded', '已上传'), ('processed', '已处理'), ('analyzed', '已分析')], default='uploaded', max_length=20)),
                ('processed_data', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
