# Generated by Django 5.2.8 on 2026-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_alter_document_options_document_file_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel表格'), ('word', 'Word文档')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('uploaded', '已上传'), ('processing', '处理中'), ('processed', '已处理'), ('error', '处理错误')], default='uploaded', max_length=20),
        ),
    ]
