# Generated by Django 5.2.8 on 2026-02-11 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_type_alter_document_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_size',
        ),
    ]
