# Generated by Django 5.2.8 on 2026-02-11 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_remove_document_file_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', '---'), ('processing', '处理中'), ('processed', '已处理'), ('error', '处理错误')], default='pending', max_length=20),
        ),
    ]
