# Generated by Django 5.2.8 on 2026-03-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_alter_document_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='content_category',
            field=models.CharField(choices=[('general', '通用文档'), ('person', '人物档案'), ('event', '校史事件'), ('organization', '机构介绍'), ('location', '校园地图'), ('subject', '学科建设')], default='general', max_length=20),
        ),
    ]
