# Generated by Django 5.2.8 on 2026-03-07 04:07

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_document_content_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-upload_time'], 'verbose_name': '文档', 'verbose_name_plural': '文档'},
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True, verbose_name='文档内容'),
        ),
        migrations.AlterField(
            model_name='document',
            name='content_category',
            field=models.CharField(choices=[('general', '通用文档'), ('person', '人物档案'), ('event', '校史事件'), ('organization', '机构介绍'), ('location', '校园地图'), ('subject', '学科建设')], default='general', max_length=20, verbose_name='内容分类'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=documents.models.document_upload_path, verbose_name='文件'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel表格'), ('word', 'Word文档')], max_length=10, verbose_name='文件类型'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_data',
            field=models.JSONField(blank=True, null=True, verbose_name='处理结果数据'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理结束时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='processing_start_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='处理开始时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='status',
            field=models.CharField(choices=[('pending', '---'), ('processing', '处理中'), ('processed', '已处理'), ('error', '处理错误')], default='pending', max_length=20, verbose_name='处理状态'),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(max_length=200, verbose_name='文档标题'),
        ),
        migrations.AlterField(
            model_name='document',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='上传时间'),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='上传者'),
        ),
    ]
