# Generated by Django 5.2.8 on 2026-03-27 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_options_alter_document_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content_category',
            field=models.CharField(choices=[('person', '人物档案'), ('event', '校史事件'), ('organization', '机构介绍'), ('location', '校园地图'), ('subject', '学科建设')], default='person', max_length=20, verbose_name='内容分类'),
        ),
    ]
