# Generated by Django 5.2.8 on 2025-11-07 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('entity_type', models.CharField(choices=[('person', '人物'), ('location', '地点'), ('event', '事件'), ('organization', '组织'), ('time', '时间')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_documents', models.ManyToManyField(to='documents.document')),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('belongs_to', '属于'), ('participated_in', '参与'), ('located_in', '位于'), ('happened_at', '发生于'), ('related_to', '相关于')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('source_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge_graph.entity')),
                ('target_entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge_graph.entity')),
            ],
        ),
    ]
