# Generated by Django 5.2.8 on 2025-11-23 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='photo_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('person', '人物'), ('location', '地点'), ('event', '事件'), ('organization', '机构'), ('subject', '学科')], max_length=20),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('belongs_to', '属于'), ('participated_in', '参与'), ('located_in', '位于'), ('happened_at', '发生于'), ('related_to', '相关于'), ('studied', '学习'), ('teaches', '教授')], max_length=20),
        ),
    ]
