# Generated by Django 5.2.8 on 2026-02-10 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_alter_document_file_type_alter_document_status'),
        ('knowledge_graph', '0002_entity_photo_url_alter_entity_entity_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='description',
        ),
        migrations.AlterField(
            model_name='entity',
            name='source_documents',
            field=models.ManyToManyField(blank=True, to='documents.document'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('属于', '属于'), ('拥有', '拥有'), ('研究', '研究'), ('主讲', '主讲'), ('毕业于', '毕业于'), ('获得', '获得'), ('负责', '负责'), ('相关于', '相关于')], max_length=20),
        ),
    ]
