# Generated by Django 5.2.8 on 2026-02-10 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0003_remove_relationship_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='confidence',
        ),
    ]
