# Generated by Django 5.2.8 on 2026-03-06 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0004_remove_relationship_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_primary',
            field=models.BooleanField(default=False, verbose_name='是否核心实体'),
        ),
    ]
