# Generated by Django 5.2.8 on 2026-03-07 04:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_alter_document_options_alter_document_content_and_more'),
        ('knowledge_graph', '0005_entity_is_primary'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxiliaryEntity',
            fields=[
            ],
            options={
                'verbose_name': '辅助实体(仅图谱)',
                'verbose_name_plural': '辅助实体(仅图谱)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_graph.entity',),
        ),
        migrations.CreateModel(
            name='CoreEntity',
            fields=[
            ],
            options={
                'verbose_name': '核心实体(前端展示)',
                'verbose_name_plural': '核心实体(前端展示)',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('knowledge_graph.entity',),
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'verbose_name': '所有实体', 'verbose_name_plural': '所有实体'},
        ),
        migrations.AlterModelOptions(
            name='relationship',
            options={'verbose_name': '关系', 'verbose_name_plural': '关系'},
        ),
        migrations.AddField(
            model_name='entity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='entity_photos/', verbose_name='上传照片'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, verbose_name='描述/简介'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='entity_type',
            field=models.CharField(choices=[('person', '人物'), ('location', '地点'), ('event', '事件'), ('organization', '机构'), ('subject', '学科')], max_length=20, verbose_name='实体类型'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=100, verbose_name='名称'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='photo_url',
            field=models.URLField(blank=True, verbose_name='网络照片URL'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='source_documents',
            field=models.ManyToManyField(blank=True, to='documents.document', verbose_name='来源文档'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='relationship_type',
            field=models.CharField(choices=[('属于', '属于'), ('拥有', '拥有'), ('研究', '研究'), ('主讲', '主讲'), ('毕业于', '毕业于'), ('获得', '获得'), ('负责', '负责'), ('相关于', '相关于')], max_length=20, verbose_name='关系类型'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='source_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='knowledge_graph.entity', verbose_name='源实体'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='target_entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='knowledge_graph.entity', verbose_name='目标实体'),
        ),
    ]
