# Generated by Django 5.2.8 on 2026-03-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0006_auxiliaryentity_coreentity_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='subtype',
            field=models.CharField(blank=True, help_text='例如：教职工、学生、杰出校友', max_length=100, null=True, verbose_name='细分类型/人物类别'),
        ),
        migrations.AddField(
            model_name='entity',
            name='title',
            field=models.CharField(blank=True, help_text='例如：教授、院长、校友', max_length=100, null=True, verbose_name='职务/头衔'),
        ),
    ]
