# Generated by Django 5.2.8 on 2026-03-07 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0007_entity_subtype_entity_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='title',
        ),
    ]
