# Generated by Django 5.2.8 on 2026-03-31 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge_graph', '0008_remove_entity_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='photo_url',
            field=models.CharField(blank=True, max_length=1000, verbose_name='网络照片URL(或路径)'),
        ),
    ]
